# Generated by Django 5.2.5 on 2025-08-19 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_author', models.CharField(blank=True, max_length=255)),
                ('num_pages', models.IntegerField(default=0)),
                ('keywords_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
