# Generated by Django 5.2.5 on 2025-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_genre_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_images_json',
            field=models.TextField(blank=True),
        ),
    ]
