# Generated by Django 5.2.5 on 2025-08-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_is_favorite_book_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorites',
            new_name='favorited_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Comic', 'Comic'), ('Motivational', 'Motivational')], max_length=50),
        ),
    ]
